FROM 763104351884.dkr.ecr.eu-central-1.amazonaws.com/pytorch-training:1.6.0-cpu-py3

RUN apt-get update && apt-get install -qq bc tree sox ffmpeg libsndfile1 libsox-fmt-mp3

#RUN pip install -U --no-cache-dir --force-reinstall torchaudio==0.6.0 # necessary cause it threw this error: OSError: /opt/conda/lib/python3.6/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

RUN pip install -e git+https://github.com/dertilo/NeMo.git@tilo#egg=nemo
RUN pip install git+https://git@github.com/dertilo/util.git
cd /mydrive/NeMo/ && pip install -r requirements/requirements.txt
cd /mydrive/NeMo/ && pip install -e .[asr]
pip install wandb
pip install "util@git+https://git@github.com/dertilo/util.git#egg=util"